### ISSUE TITLE
Settings should be in the ControlPanels Settings Tab

### ISSUE THREAD

**Issue by pmario** [BurningTreeC/TiddlyFlex#1]
TW now allows us to create new tabs in the CP -> Settings area. I've implemented it for [one of my plugins: link-to-tabs](https://wikilabs.github.io/editions/link-to-tabs/)

If you import this plugin to tiddlywiki.com you can see how it is implemented and you can use the tab-link-icon to open the different tiddlers to see the details. 

`$:/tags/ControlPanel/SettingsTab` is the tag for tiddlers to show up in the CP -> Settings area

`$:/tags/ControlPanel/WikiLabs` ... That will be the tag for my plugins, to creates "sub-tabs" under "WikiLabs" 

![image](https://github.com/BurningTreeC/TiddlyFlex/assets/374655/eaf0e16a-ae1e-4f05-b857-55daae20ca0d)

**Comment by BurningTreeC** [comment]
Hi @pmario and thanks for the first issue!
Yes the settings should go there, I agree.

**Comment by BurningTreeC** [comment]
It will take some time until I have addressed all my outstanding issues with this plugin - then I'll add a ControlPanel thingy

**Comment by BurningTreeC** [comment]
Hi @pmario - I've now added the settings in the ControlPanel > Settings > TiddlyFlex
