### ISSUE TITLE
Open tiddler by URL

### ISSUE THREAD

**Issue by MagicJF** [BurningTreeC/TiddlyFlex#2]
Hi, not an issue but an unusual behaivour.

Normally you can acces individual tiddlers by concatenating the URL of the wiki + the name of the tiddler, as follows:
![ok](https://github.com/BurningTreeC/TiddlyFlex/assets/92638213/0138c4bc-e1c3-4c14-89f0-4ecac6656df7)

However, when TiddlyFlex Layout is activated, It opens the last retained story, no matter the URL, as follows:
![ko](https://github.com/BurningTreeC/TiddlyFlex/assets/92638213/12c758f8-8331-4337-8453-1874864b5068)

In my usecase I access specific tiddlers from URL and would be nice to not lose this feature when TiddlyFlex is on

**Comment by BurningTreeC** [comment]
Hi @MagicJF - thanks for reporting!
This will be added!

Thanks,
Simon

**Comment by BurningTreeC** [comment]
Hi @MagicJF , I've now addressed this issue. It's not perfect how I did it and I will think about it again, but it's addressed :+1:

**Comment by MagicJF** [comment]
Thxs! 
I appreciate it :)

**Comment by MagicJF** [comment]
Thxs! 

I apreciate it :)
